//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamesApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Games
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Games()
        {
            this.Rating = new HashSet<Rating>();
        }
    
        public int Game_code { get; set; }
        public Nullable<int> Developer_code { get; set; }
        public Nullable<int> Publisher_code { get; set; }
        public Nullable<int> Genre_code { get; set; }
        public string Game_name { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Release_date { get; set; }
        public bool Game_status { get; set; }
        public string Status_game
        {
            get
            {
                return (Game_status) ? "Released" : "Announced";
            }
        }
        public string Picture { get; set; }
        public Nullable<float> Rate { get; set; }
    
        public virtual Developers Developers { get; set; }
        public virtual Genres Genres { get; set; }
        public virtual Publishers Publishers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rating> Rating { get; set; }
    }
}
