//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamesApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public int Rating_code { get; set; }
        public Nullable<int> User_code { get; set; }
        public Nullable<int> Game_code { get; set; }
        public Nullable<float> User_rating { get; set; }
    
        public virtual Games Games { get; set; }
        public virtual Users Users { get; set; }
    }
}
